/*******************************************************************************
* NOME DO ARQUIVO :        modules/def/dialog.pwn
*
* DESCRIÇÃO :
*       Organizar os ID de dialogo para que não aja mais de um dialogo com
*       mesmo id.
*
* NOTAS :
*       -
*/

enum
{
    DIALOG_LOGIN,
    DIALOG_REGISTER,
    DIALOG_BANNED,
    DIALOG_COLORS,
    DIALOG_CREDITS,
    DIALOG_FORUM,
    DIALOG_COMMAND_LIST,

    DIALOG_TUNING,
    DIALOG_TUNING_PAINTJOB,
    DIALOG_TUNING_COLOR,
    DIALOG_TUNING_EXHAUST,
    DIALOG_TUNING_FBUMP,
    DIALOG_TUNING_RBUMP,
    DIALOG_TUNING_ROOF,
    DIALOG_TUNING_SPOILER,
    DIALOG_TUNING_SKIRT,
    DIALOG_TUNING_BULLBAR,
    DIALOG_TUNING_WHEEL,
    DIALOG_TUNING_NITRO,
    DIALOG_TUNING_HOOD,
    DIALOG_TUNING_VENT,
    DIALOG_TUNING_LIGHT,
    DIALOG_VEHICLE_LIST,
    DIALOG_FIGHTING_LIST,

    DIALOG_LOGIN_PASSWORD,

    DIALOG_REGISTER_GENDER,
    DIALOG_REGISTER_PASSWORD,
    DIALOG_REGISTER_AGE,
    DIALOG_REGISTER_EMAIL,

    DIALOG_RACE_CREATOR,
    DIALOG_RACE_CREATOR_PRIZE,
    DIALOG_RACE_PRIZE_VALUE,
    DIALOG_RACE_CREATOR_CONFIG,
    DIALOG_RACE_CONFIG_CP_TYPE,
    DIALOG_RACE_CONFIG_CP_SIZE,
    DIALOG_RACE_CONFIG_CP_NAME,
    DIALOG_RACE_CONFIG_VMODEL,

    DIALOG_RACE,
    DIALOG_RACE_LEADERBOARD,

    DIALOG_EVENT_CREATOR,
    DIALOG_EVENT_CREATOR_WEAPON,
    DIALOG_EVENT_CR_WP_SLOT_0,
    DIALOG_EVENT_CR_WP_SLOT_1,
    DIALOG_EVENT_CR_WP_SLOT_2,
    DIALOG_EVENT_CR_WP_SLOT_3,
    DIALOG_EVENT_CR_WP_SLOT_4,
    DIALOG_EVENT_CR_WP_SLOT_5,
    DIALOG_EVENT_CR_WP_SLOT_6,
    DIALOG_EVENT_CR_WP_SLOT_7,
    DIALOG_EVENT_CR_WP_SLOT_8,
    DIALOG_EVENT_CR_WP_SLOT_9,
    DIALOG_EVENT_CR_WP_SLOT_10,

    DIALOG_EVENT_CREATOR_SPAWN,
    DIALOG_EVENT_CREATOR_PRIZE
}
